#!/bin/bash

SCRIPT_DIR=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
INCLUDE_DIR=$SCRIPT_DIR/src/include

function testFiles() {
  printf "\033c"
  make -s build

  for test in `find build/*`;do
    $test
  done
}

testFiles
while RESULT=$(inotifywait -qr -e MODIFY --exclude .*\\.swp $SCRIPT_DIR)
do
  testFiles
done
